# Generated by Django 6.0.5 on 2026-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('order_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='order_items', to='order.order'),
        ),
    ]
