# Generated by Django 6.0.5 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderitem_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orders',
            field=models.ManyToManyField(related_name='order_items', to='order.order'),
        ),
    ]
