# Generated by Django 6.0.5 on 2026-05-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', to='order.orderitem'),
        ),
    ]
