# Generated by Django 6.0.5 on 2026-05-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_orders_order_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderSummary',
        ),
    ]
