# Generated by Django 6.0.5 on 2026-05-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_order_ordersummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderSummary',
            new_name='Cart',
        ),
    ]
